version: '3.7'

services:
  web:
    build: .
    container_name: goods_categorizer_web
    ports:
      - 8000:8000
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
  qdrant:
    image: generall/qdrant:3.4
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
