version: "3.7"

services:
  web:
    build: .
    container_name: goods_categorizer_web
    environment:
      - QDRANT_HOST=qdrant_categorizer
    depends_on:
      - qdrant_categorizer
    networks:
      - qdrant-net

  qdrant_categorizer:
    image: generall/qdrant:v0.3.5
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

    networks:
      - qdrant-net

networks:
  qdrant-net:
    external:
      name: qdrant-net
